### ISSUE TITLE
A way to give month and day names

### ISSUE THREAD

**Issue by tapz** [maggialejandro/react-native-calendario#129]
Now it's impossible to localize the calendar if the UI language is something else than en, es, br, fr. Would be nice to be able to give an array of month names and an array of weekday names.

**Comment by tapz** [comment]
And specify the first day of week.

**Comment by tapz** [comment]
Didn't realize these properties already existed. Would be nice to have all props listed in the readme.

**Comment by red-made** [comment]
Hi, please tell me how to set custom months and days name. Thanks!
