### ISSUE TITLE
Please no FlatList

### ISSUE THREAD

**Issue by tapz** [maggialejandro/react-native-calendario#130]
Would be nice if the calendar was not wrapped in a FlatList. I would rather wrap it myself to a ScrollView. Not I get this warning and need to implement a one row FlatList.

> WARN  VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

**Comment by maggialejandro** [comment]
Hi @tapz 
The problem using a ScrollView is the lack of possible optimizations that `FlatList` offers like `getItemLayout` `initialNumToRender` `viewabilityConfig` and so on.
