### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by tapz** [maggialejandro/react-native-calendario#131]
When I wrapped Calendar to FlatList instead of ScrollView the calendar started to cause the following error when trying to set startDate to anything in the visible range. Any idea what might cause this?

```
TypeError: undefined is not a function

This error is located at:
    in Calendar (at MyFile.js:35)
    ....
```

**Comment by maggialejandro** [comment]
Hi @tapz
Could you reproduce the issue on an expo [snack](https://snack.expo.io/) and share the link please?
