### ISSUE TITLE
1.0.0 renders as undefined

### ISSUE THREAD

**Issue by tapz** [maggialejandro/react-native-calendario#138]
1.0.0 renders as undefined, but 0.6.0 works. Due to this with 1.0.0 the app crashes with an error that the rendered is not an object nor a string, but undefined. I have the Calendar component inside a ScrollView container.

**Comment by maggialejandro** [comment]
Hi @tapz 
Version 1.0.0 introduced a breaking change
Now you need to import `Calendar` like this
https://github.com/maggialejandro/react-native-calendario/blob/2c9cdf9cb73132af731839ebfa77696b6fec7d8d/example/App.tsx#L3

Sorry about that
