### ISSUE TITLE
Select multiple dates out of range

### ISSUE THREAD

**Issue by ryanmagoon** [maggialejandro/react-native-calendario#148]
Hello!

Is there a way to have multiple selections on the calendar? Reading through the code, it seems like there's no way to do that currently. If not, is this a feature you'd be interested in me implementing?

**Comment by maggialejandro** [comment]
Hi @ryanmagoon 
You are right, you cannot select multiple dates or date ranges.

If you want to start implementing that feature take a look at branch `v2` , it'll soon be merged
