### ISSUE TITLE
Overlapping month name

### ISSUE THREAD

**Issue by tapz** [maggialejandro/react-native-calendario#149]
April title is positioned on top of the last week of March. When I scroll down to May, it's title is positioned correctly.

Version: 1.0.0 in Android

![calendarbug](https://user-images.githubusercontent.com/11726387/75637249-fc09b600-5c2d-11ea-94ab-602597a2f434.png)

**Comment by maggialejandro** [comment]
Hi @tapz , I think you should set a higher `monthHeight` value

**Comment by tapz** [comment]
So I should know each month height? Why was February correct and May is correct?

**Comment by maggialejandro** [comment]
@tapz exactly. Setting each row height is a big performance [optimization](https://reactnative.dev/docs/flatlist#getitemlayout)

The solution for now is to set a higher height number, otherwise `getItemLayout` should calculate how many rows does it has
