### ISSUE TITLE
The Calendar language  When to support chinese?

### ISSUE THREAD

**Issue by bucengfangqi** [maggialejandro/react-native-calendario#156]
**The Calendar language  When to support chinese?** 😘😘😘

```
// month   
case 'zh':
  return [
    '一月',
    '二月',
    '三月',
    '四月',
    '五月',
    '六月',
    '七月',
    '八月',
    '九月',
    '十月',
    '十一月',
    '十二月',
  ];
// week
case 'zh':
  return ['日', '一', '二', '三', '四', '五', '六'];
```

**like this~~**
![image](https://user-images.githubusercontent.com/22071679/77624049-30963680-6f7c-11ea-9eaa-0e241c9d0b91.png)

**Comment by bucengfangqi** [comment]
Can add week language support?

**Comment by bucengfangqi** [comment]
case 'zh':
      return [
        '一月',
        '二月',
        '三月',
        '四月',
        '五月',
        '六月',
        '七月',
        '八月',
        '九月',
        '十月',
        '十一月',
        '十二月',
      ];

**Comment by bucengfangqi** [comment]
case 'zh':
      return ['日', '一', '二', '三', '四', '五', '六'];

**Comment by bucengfangqi** [comment]
this Can work well with [createMaterialTopTabNavigator](https://reactnavigation.org/docs/4.x/material-top-tab-navigator)
![image](https://user-images.githubusercontent.com/22071679/77649829-71567580-6fa5-11ea-9900-c730912970f2.png)

**Comment by maggialejandro** [comment]
Hi @bucengfangqi , I'll add Chinese lang asap. You could create a PR to the [month](https://github.com/maggialejandro/react-native-month) repo too ;)

**Comment by maggialejandro** [comment]
https://github.com/maggialejandro/react-native-calendario/pull/160
