### ISSUE TITLE
tries to require `react-native`, but there are several files providing this module

### ISSUE THREAD

**Issue by httol** [maggialejandro/react-native-calendario#17]
react-native:0.51.1
install react-native-calendario, then show this error, "tries to require `react-native`, but there are several files providing this module", I find that the in the file react-native-calendario/node_moudles/react-native/package.json ,this name 'react-native ' conflict with my project node_modules/react-native/package.json, is there the problem??

**Comment by maggialejandro** [comment]
Can you try ```npm start -- --reset-cache``` ?

**Comment by maggialejandro** [comment]
Fixed in version 0.0.14
