### ISSUE TITLE
after calling onChange hooks func, no selected date container appears

### ISSUE THREAD

**Issue by Zakyyy** [maggialejandro/react-native-calendario#175]
### Current behaviour
I added a text field above the calendar to show the selected date, 
and in onChange function I call the set function using useState HOOKS
but the selected container around the selected day doesn't appear unless I pressed on the day 
twice.

### Expected behaviour
After I press on a day the circular container around it should appear
### Code sample

<View style={styles.selectedDateContainer}>
          <Text>{selectedDate}</Text>
        </View>
        <Calendar
          onChange={(date) => {
            // setTimeout(() => {
            setSelectedDate(date.startDate.toDateString())
            // }, 500)
          }}
          minDate={new Date(2018, 3, 20)}
          startDate={new Date(2018, 3, 30)}
          endDate={new Date(2018, 4, 5)}
          disableRange={true}
/>
### Your Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 179.43 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by maggialejandro** [comment]
Hi @Zakyyy , could you reproduce the issue on the example project and share the code?
Thanks in advance

**Comment by Zakyyy** [comment]
@maggialejandro 
<Calendar
	onChange={(range) => {
	   setSelectedDate(range.startDate.toString()) // hooks function
}}
minDate={new Date()}
disableRange={true}
/>

**Comment by Zakyyy** [comment]
@maggialejandro my bad sorry I should update start and end date
