### ISSUE TITLE
Unable to rerender component after changing minDate or startingMonth props

### ISSUE THREAD

**Issue by oguzhanturgut** [maggialejandro/react-native-calendario#177]
Is there any way to force calender rerender after changing one of its props?

**Comment by oguzhanturgut** [comment]
I am trying to control component from screen but coul not manage to. Calendar does not rerender after changing props
```
const CalenderPicker = ({calendarProps}) => {

  const {minDate, maxDate, startingMonth} = calendarProps;

  return (
    <Calendar
      onChange={range =>
        console.log({
          startDate: moment(range.startDate).utc(),
          endDate: moment(range.endDate ?? range.startDate).utc(),
        })
      }
      minDate={minDate}
      maxDate={maxDate}
      startingMonth={startingMonth}
      numberOfMonths={13}
      // initialListSize={13}
      firstDayMonday
      showWeekdays={false}
      theme={THEME}
    />
  );
};
```

**Comment by ztcollazo** [comment]
I'm having this same issue also. I'm using Expo and Next.js, trying to create a calendar component with switchable months (because react-native-calendars wasn't cooperating). I'm rendering one month at a time, and then when the user presses the button, it switches to the next month. The logic is all working correctly, but the `startingMonth` prop isn't changing or even working when I set it manually.

**Comment by maggialejandro** [comment]
> I'm having this same issue also. I'm using Expo and Next.js, trying to create a calendar component with switchable months (because react-native-calendars wasn't cooperating). I'm rendering one month at a time, and then when the user presses the button, it switches to the next month. The logic is all working correctly, but the `startingMonth` prop isn't changing or even working when I set it manually.

You could try [react-native-month](https://github.com/maggialejandro/react-native-month) instead

**Comment by ztcollazo** [comment]
Thanks, I'll check this out. If it doesn't work, then we'll know that it's a problem with react-native-month, so I'll just open an issue there instead.

**Comment by ztcollazo** [comment]
Yep, It worked. I did have to do a bit of fiddling to figure it out, so for anyone looking to do this in the future: having a state variable `date` and then changing `date` and using `getMonth` and `getFullYear` doesn't work (which is a React thing, not a `react-native-month` thing). Instead, you need to have two separate state variables (eg: `month` and `year`) and use those.
