### ISSUE TITLE
Selected Day presents 1 days before selected

### ISSUE THREAD

**Issue by Osher671279** [maggialejandro/react-native-calendario#178]
### Code sample

Took the code from your Docs

### Screenshots (if applicable)

[https://imgur.com/a/fZD0Vl7](url)
[https://imgur.com/Nky6vFY](url)

### What have you tried

tried to search on google how to convert to local time in React native, couldn't find anything useful.

### Your Environment

Visual studio code - React native Expo

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

**Comment by nehalahmed929** [comment]
same issue with me

**Comment by nehalahmed929** [comment]
i was also having this issue. but when i passed the incooming date in moment funtion. it showed just fine

onChange={(range)=>{
setStartDate(moment(range.startDate).format("YYYY-MM-DD"))

}

}
