### ISSUE TITLE
Can i select only 1 Day as range?

### ISSUE THREAD

**Issue by Osher671279** [maggialejandro/react-native-calendario#179]
Hey,
If i would like to select only 1 day as range, for example:
Im a business owner who open 1 day a week and i want to select only this day, am i able to do this?

Whenever im doing it the selected date is disappear and the app is stuck.

dont know how to change the label im sorry its not a bug

**Comment by Osher671279** [comment]
Hey Thanks for the fast replay, im attaching a video(Dont be scared from the Hebrew)

https://vimeo.com/463549969 (Tell me if there is a problem)

What i want to do is this:
I want the Range to be enabled, meaning that i can still choose date range but i would like to choose only 1 day if i want to

**Comment by maggialejandro** [comment]
That's weird
Are you using the latest version?
Could you share a [snack](https://snack.expo.io/) or reproduce that behavior on the example app?

**Comment by Osher671279** [comment]
My code is bit complicated to add to Snack :( its a whole App 
Please mind that if i pick a range its working

Do you have a Discord or WhatsApp that we can talk more directly?

**Comment by Osher671279** [comment]
This is the implement of the Range(Working when i choose more then 1 day):
`    let end = "";
    const start2 = range.startDate;
    console.log("=======", range);

    let end2 = "";
    const start = range.startDate.toString();
    if (range.endDate != null) {
      end = range.endDate.toString();
      end2 = range.endDate;
    }`

Calendar:
`  onChange={(range) => {
            setStartEndDates(range);
          }}
          minDate={new Date()}
          startDate={new Date()}
          endDate={new Date()}
          disableOffsetDays={true}
          // disabledDays={DISABLED_DAYS}`
