### ISSUE TITLE
How to implement the use of DisableRange prop

### ISSUE THREAD

**Issue by Osher671279** [maggialejandro/react-native-calendario#180]
Hey
Im currently trying to implement the use of DisableRange prop.
I set it to true as follow:

<Calendar
            onChange={(startDate) => {
              handleOneDay(startDate); // Here is the problem
            }}
            minDate={new Date()}
            startDate={new Date()}
            endDate={new Date()}
            disableOffsetDays={true}
            **disableRange={true}**

But what im trying to do is to pass the selected date to a function that will handle it and treat the selected date as start date and end date.

suggestions??

**Comment by maggialejandro** [comment]
Hi
The calendar should receive the selected date
`startDate={this.props.startDate}` or `startDate={this.state.startDate}` maybe
