### ISSUE TITLE
0.56 cant work

### ISSUE THREAD

**Issue by tianweicc** [maggialejandro/react-native-calendario#20]
0.56 cant work

**Comment by maggialejandro** [comment]
Can you send a stacktrace?
Also the output of 
```bash
react-native info
```

**Comment by tianweicc** [comment]
@maggialejandro yarn end 
![850f0bae264d053aa871a461d271313b](https://user-images.githubusercontent.com/17263719/44562532-8e551200-a78c-11e8-9ed8-f3c219b6f5b8.jpg)

**Comment by maggialejandro** [comment]
Could you reproduce the error [here](https://github.com/maggialejandro/react-native-calendario/tree/fix-react-native-0.56.0)? or upload a some code?
It throws me a different [error](https://github.com/facebook/react-native/issues/20607)
