### ISSUE TITLE
Disabled dates not working

### ISSUE THREAD

**Issue by nehalahmed929** [maggialejandro/react-native-calendario#203]
I passed disabled dates as

disabledDays={["2020-12-07T19:00:00.000Z", 2020-12-14T19:00:00.000Z"]}

but it didn't worked

**Comment by maggialejandro** [comment]
Hi @nehalahmed929 
Try using this format
https://github.com/maggialejandro/react-native-calendario/blob/0e5b6349b8b194f5e8a39fb59c288a554c9ad0d4/example/App.tsx#L62-L65

**Comment by nehalahmed929** [comment]
thanks a lot it worked!
