### ISSUE TITLE
Can't set disable days for next month

### ISSUE THREAD

**Issue by dody87** [maggialejandro/react-native-calendario#220]
### Current behaviour
I send a list of disable dates like this:

`{"2021-06-09": true, "2021-06-10": true, "2021-06-11": true, "2021-06-12": true, "2021-06-13": true, "2021-06-14": true, "2021-06-15": true, "2021-06-23": true, "2021-06-24": true, "2021-06-25": true, "2021-06-26": true, "2021-06-27": true, "2021-06-28": true, "2021-06-30": true, "2021-07-01": true, "2021-07-02": true}`

However, it's just rendering the current month correctly (disabled) but not the days from the next month.

### Expected behavior

The expected behavior is to show disable the loaded dates for next month.

### Code sample

`<Calendar
                            onChange={this.callbackDate}
                            minDate={new Date()}
                            locale='en'
                            disabledDays={this.state.dayDisabled}
                        />`

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/3058417/121555728-a2c03300-c9e9-11eb-9696-4f1cf924eb10.png)

### Your Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

**Comment by maggialejandro** [comment]
Sorry for the delay, can you test again? it should be fixed on [v2.1.3](https://github.com/maggialejandro/react-native-calendario/releases/tag/v2.1.3)

**Comment by dody87** [comment]
I will take a look and go back to you. Thanks!
