### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by koswarabilly** [maggialejandro/react-native-calendario#27]
Rather than using YYYY-MM-DD, i suggest you have other option to read milliseconds too. 
It will help so much, give me your thought

**Comment by maggialejandro** [comment]
Why would you want to use the time of a Date?

**Comment by koswarabilly** [comment]
For me running around with universal format of milliseconds (ex: 1536197803780) is better than having a strict format. But I do not say that having yyyy-mm-dd format is bad though, just a request from your fellow library fans. Would it be possible?

**Comment by maggialejandro** [comment]
Yes, that's correct. You can parse your date using moment like this
```javascript
moment(yourDate).format('YYYY-MM-DD');
```

I'll close this for now, feel free to open another issue if you have any suggestions, etc
