### ISSUE TITLE
How to scroll to Specific month?

### ISSUE THREAD

**Issue by unigisper8** [maggialejandro/react-native-calendario#277]
I'd like to show user History on the Calendar.
So, the calendar should be displayed from the User's Created Account day to the next few months.
Let's say user created the account 3 month's ago and it's Oct now. 
Then, the first month to render will be July.
I want to scroll to Oct when user open the Callendar and make the calendar to be scrolled.
How can I get this feature?

**Comment by maggialejandro** [comment]
You can now use FlatList's forwarded `ref`
You need to calculate the index for the month you want to navigate to.

Feel free to re-open this if you have any issues
