### ISSUE TITLE
Showing blank screen on initial launch with month names only

### ISSUE THREAD

**Issue by official-ravi** [maggialejandro/react-native-calendario#291]
### Current behaviour

On initial launch black screen with month name is coming up and when user is touching the screen or scrolling a little even its getting rendered properly.

### Expected behaviour

It should render properly on initial launch only.

### Code sample

for code sample I am using the code available in example folder of this repo

https://github.com/maggialejandro/react-native-calendario/blob/master/example/App.tsx

### Screenshots (if applicable)

Please check attached screenshot for more details.
![simulator_screenshot_58FAF323-A0AF-46DD-B1F9-7C068BBBA54B](https://user-images.githubusercontent.com/79018779/158811829-bc575eb8-080d-485b-8e84-7b09a1f28159.png)

**Comment by chganesh** [comment]
@maggialejandro  Me also facing same issue 
![unnamed (10)](https://github.com/maggialejandro/react-native-calendario/assets/14010143/9e0c3a6d-0f2a-4554-a39c-0691962d6738)


"react-native-calendario": "^3.5.2"

<Calendar
                        data={[{ id: 'calendar' }]}
                        onPress={handleChangeDate}
                        startDate={new Date(selectedStartDate)}
                        endDate={new Date(selectedEndDate)}
                        startingMonth={moment().clone().subtract(11, 'months').startOf('month').format('YYYY-MM-DD')}
                        monthHeight={370}
                        numberOfMonths={12}
                        //minDate={new Date(selectedStartDate)}
                        //maxDate={selectedMaxDate}
                        initialListSize={4}
                        theme={THEME}
                        showWeekdays={true}
                        firstDayMonday={true}
                        //disableRange={true}
                        markedDays={markedVitalDates}
                    //disabledDays={disabledDays}
                    />
