### ISSUE TITLE
The component does not re-render

### ISSUE THREAD

**Issue by frodoe7** [maggialejandro/react-native-calendario#292]
Here's the code base

```
  const [startDate, setStartDate] = useState<Date>(undefined);
  const [endDate, setEndDate] = useState<Date>(undefined);

  const onDayPress = (day: Date) => {
    setEndDate(new Date(day));
    setStartDate(new Date(day));
  };

            <Calendar
              onPress={onDayPress}
              startDate={startDate}
              endDate={endDate} />
```

on pressing on any day, the component does not re-render

**when I press CMD + S, and save**

**the hot reload re-render the component and show the expected output**

**Comment by maggialejandro** [comment]
Hi @frodoe7 
could you share a more detailed example? or even better fork the project and update _example/App.tsx_

**Comment by frodoe7** [comment]
@maggialejandro 
The example built with class component pattern
did you try that calendar component with the hooks ?

not sure if this will reproduce the issue
but the project which I work on is big, so it's a bit hard to extract that calendar component part form it

**Comment by frodoe7** [comment]
@maggialejandro 
I mean if you have something similar to that example/app.tsx
but built with functional hooks

**Comment by maggialejandro** [comment]
Could you try [this](https://snack.expo.dev/sUnmdO1Xw) please?

**Comment by frodoe7** [comment]
@maggialejandro 
I did not find it working 😑

**Comment by maggialejandro** [comment]
@frodoe7 that example is working
could you reproduce it on a Snack?

https://user-images.githubusercontent.com/3394748/163828604-4e9d41fe-27ee-485c-9e60-b42b1dfa1feb.mov

**Comment by frodoe7** [comment]
@maggialejandro 
It select the pre-pressed day
I mean if I clicked on day 7 , it select day 6

however it's not the issue at all
the final target is to select a range
In that example, every time you click it only set the startDate

also as initial dates (start & end), it does not render that range on the calendar

**Comment by maggialejandro** [comment]
@frodoe7 
Try [this](https://snack.expo.dev/irUGVdcD_)

**Comment by frodoe7** [comment]
@maggialejandro 
Nice, It's working well with the initial data

however when I select multiple times, it does not generate the range again

**Comment by maggialejandro** [comment]
I guess it's a logic issue on `handleChangeDate` callback. Could you debug it and get back to me if no success?

**Comment by frodoe7** [comment]
@maggialejandro 
Sure, will debug it and get back to you

**Comment by frodoe7** [comment]
@maggialejandro 

I caught the issue in my code

it's related to the startingMonth attribute,
when I set it to a fixed date, everything works fine
when I try to custom it, it shows this bug

this one working fine
                startingMonth="2020-01-01"

this one fire that bug, startingMonth is a JS Date
                // startingMonth={
                //   startingMonth.getFullYear().toString() +
                //   '-' +
                //   (startingMonth.getMonth() + 1).toString().padStart(2, '0')
                // }

Anyway you can close that issue, I think not related to the library
