### ISSUE TITLE
Calendar doesn't appear until press

### ISSUE THREAD

**Issue by minuitagency** [maggialejandro/react-native-calendario#297]
### Current behaviour

When I start my app the calendar is blank, I have to press on the screen for it to appear.

### Expected behaviour

I expect the calendar to be displayed without any user interaction.

### Code sample

<img width="691" alt="image" src="https://user-images.githubusercontent.com/38316888/169798648-cb04da0c-6233-4532-95c2-23d99da77c47.png">

### What have you tried

I have tried removing all the props one by one, using a useCallback but it doesn't change anything.

### Your Environment

System:
    OS: macOS 12.3.1
    CPU: (20) x64 Apple M1 Ultra
    Memory: 133.82 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.0 - ~/.nvm/versions/node/v12.22.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.22.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: javac 11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by maggialejandro** [comment]
Could you paste the whole code sample please?
Where is `SelectDatesBottomSheet` used?

**Comment by minuitagency** [comment]
![image](https://user-images.githubusercontent.com/38316888/169817569-5930646f-3536-4d37-9106-781de6ca4a72.png)

Let me know if it's readable for you, 

Thanks again, 

Théo

**Comment by minuitagency** [comment]
https://user-images.githubusercontent.com/38316888/169861275-875399e5-d70e-43ce-bf9d-879cbe2310f5.MP4

Sure! Here you go, thanks again, 

Théo

**Comment by minuitagency** [comment]
Some idea @maggialejandro ? Thanks

**Comment by maggialejandro** [comment]
@minuitagency no sorry, it'll need to be debugged

**Comment by chganesh** [comment]
Uploading az_recorder_20240704_192143 (1).mp4…

@maggialejandro  i am getting this issue. if i press it will loading and loading also taking to munch time 
![unnamed](https://github.com/maggialejandro/react-native-calendario/assets/14010143/7045423b-4238-4330-85c1-6fd53f3b188a)

**Comment by chganesh** [comment]
https://github.com/maggialejandro/react-native-calendario/assets/14010143/43bf2e39-42a3-42e8-ac63-9b6a262ffbd9

check this one @maggialejandro

**Comment by maggialejandro** [comment]
> az_recorder_20240704_192143.1.mp4 
> check this one @maggialejandro

Hi! Does that happen only in dev mode or also in release mode? Are you rendering the calendar inside a Modal or another component?

**Comment by chganesh** [comment]
Both environment its working like that only here is my code 

const customDayBottomSheet = () => {
        return (<BottomSheet
            ref={bottomSheetModalRef}
            index={0}
            enablePanDownToClose={false}
            enableHandlePanningGesture={false}
            onAnimate={(fromIndex, toIndex) => {
                if (fromIndex > toIndex && toIndex === -1) {
                    closeDayBottomSheet()
                }
            }}
            backgroundStyle={{ backgroundColor: '#FFFFFF' }}
            backdropComponent={renderBackdrop}
            ref={bottomSheeDaytModalRef}
            snapPoints={['80%', '83%']} >

            <View style={{ paddingHorizontal: 16, justifyContent: 'space-between', flexDirection: 'row', alignItems: 'center', marginBottom: 5 }}>
                <Pressable
                    onPress={() => {
                        calculateCurrentDayData(route?.params?.allvitalData, selectedVitalName, '', dayRange.start);
                        closeDayBottomSheet()
                    }}>
                    <GlobalText.DemoTextBookBlack style={{ fontSize: 18, fontWeight: '800', color:range.start!=range.end?colors.abhaButtonColor:colors.lightGray }}>Done</GlobalText.DemoTextBookBlack>
                </Pressable>
                <Pressable
                    onPress={() => {
                        //setShowBottomSheet(false)
                        closeDayBottomSheet();
                    }}>
                    <NativeIcon iconName={'x-circle'} iconLib={'Feather'} iconSize={25} iconColor={colors.red} />
                </Pressable>
            </View>
            <Divider style={styles.dividerStyle} />
            <BottomSheetFlatList // * BottomSheetFlatList needed for Android scroll support
                data={[{ id: 'calendar' }]}
                contentContainerStyle={{ paddingBottom: 10, marginTop: 10 }}
                style={{ backgroundColor: '#ffffff' }}
                renderItem={() => (
                    <Calendar
                        data={[{ id: 'calendar' }]}
                        onPress={handleDateChange}
                        startDate={dayRange.start}
                        endDate={dayRange.end}
                        startingMonth={moment().clone().subtract(11, 'months').startOf('month').format('YYYY-MM-DD')}
                        monthHeight={370}
                        numberOfMonths={12}
                        //minDate={new Date(selectedStartDate)}
                        //maxDate={selectedMaxDate}
                        initialListSize={4}
                        theme={THEME}
                        showWeekdays={true}
                        firstDayMonday={true}
                        //disableRange={true}
                        markedDays={markedVitalDates}
                        disabledDays={DISABLED_DAYS}
                    />
                )}
                keyExtractor={item => item.id}
            />

        </BottomSheet>

        )
    }

**Comment by maggialejandro** [comment]
if you are only using 12 months, can you try using this prop ? `renderAllMonths`

**Comment by chganesh** [comment]
@maggialejandro  When I pass renderAllMonths, I also encounter the same issue when I pass startDate and EndDate as the default dates.
The operation is fine when I pass an empty string('') startDate and endDate.


 Some times initial loading it was not rendering remaining months its rendering only first two months

**Comment by maggialejandro** [comment]
In order to debug the issue, could you share a project or Expo Snack?
In the meantime, could you set `initialListSize={12}` ?

**Comment by chganesh** [comment]
@maggialejandro here is my snippet

 <Calendar
                        data={[{ id: 'calendar' }]}
                        onPress={handleChangeDate}
                        startDate={range.start}
                        endDate={range.end}
                        startingMonth={moment().clone().subtract(11, 'months').startOf('month').format('YYYY-MM-DD')}
                        monthHeight={370}
                        numberOfMonths={12}
                        renderAllMonths
                        initialListSize={12}
                        theme={THEME}
                        showWeekdays={true}
                        firstDayMonday={true}
                        disableRange={true}
                        markedDays={markedVitalDates}
                        disabledDays={DISABLED_DAYS}
                    />

The calendar won't display until we touch the screen if I change the start and end dates, but otherwise it's fine.
like 
setRange({
            start:03-07-2024,
             end:09-07-2024
         })

**Comment by maggialejandro** [comment]
Can you share a project on GitHub where the issue occurs? Or reproduce it on https://snack.expo.dev/?

**Comment by chganesh** [comment]
https://github.com/maggialejandro/react-native-calendario/assets/14010143/d6b1b260-cd43-44da-a7b3-a597f0bc0bf1

<Calendar
data={[{ id: 'calendar' }]}
onPress={handleChangeDate}
startDate={03-07-2024}
endDate={09-07-2024}
startingMonth={moment().clone().subtract(11, 'months').startOf('month').format('YYYY-MM-DD')}
monthHeight={370}
numberOfMonths={12}
renderAllMonths
initialListSize={12}
theme={THEME}
showWeekdays={true}
firstDayMonday={true}
disableRange={true}
markedDays={markedVitalDates}
disabledDays={DISABLED_DAYS}
/> 
@maggialejandro  while setting start date end date issue was occurring for me
