### ISSUE TITLE
disabledDays not working

### ISSUE THREAD

**Issue by sefailyasoz-upayments** [maggialejandro/react-native-calendario#304]
Hi, 

react native version: "0.67.4", and calendario version: "^3.1.0"

I'm giving data to disabledDays prop as ["17-08-2022"] and expecting August 17 to be disabled but it is not working. I've tried many other ways as data type nothing seems to be working. Any suggestion ?

**Comment by UmarLE** [comment]
work for me as '2022-09-01': {disabled: true}

**Comment by sefailyasoz-upayments** [comment]
Thanks guys, this helped me a lot 🙏🏻
