### ISSUE TITLE
Unable to set starting month?

### ISSUE THREAD

**Issue by justdan0227** [maggialejandro/react-native-calendario#312]
The following code won't scroll back past Sept. (ios simulator)

return (
    <Calendar
      minDate={new Date(2022, 1, 1)}
      startDate={new Date(2022, 9, 1)} 
      theme={{
        activeDayColor: {
          color: 'white',
          backgroundColor: 'blue',
        },
        activeDayColor: {},
        monthTitleTextStyle: {
          color: 'blue',
          fontWeight: '300',
          fontSize: 23,
        },
      }}
      startingMonth={new Date(2022, 1, 1)}
    />
  );

**Comment by maggialejandro** [comment]
`startingMonth` is a string with this format `'2019-11-01'`
