### ISSUE TITLE
disableOffsetDays theming issue + range issue

### ISSUE THREAD

**Issue by mvolonnino** [maggialejandro/react-native-calendario#344]
### Current behaviour

When utilizing theme, i have dark and light mode. Cant figure out from typings or docs how to change the disabled offset background color. Is always white

Also when selecting range, that extends more than the month, the offset days also highlight which is confusing UI.

i select Oct 31 - Nov 4th, and all the offset days get selected as well, so in my case, it shows Oct 31 start of highlight - 1 2 3 4 of the offset days are highlighted, than november month starts at 29 (oct) 30 (oct) 31 (oct) then 1. All those days in november are selected too, so it looks like 29th 30th are also selected when it should just be 31st-4th of Nov.

### Expected behaviour

offset days of the month should not get highlighted when range selection

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Screenshots (if applicable)

This video showcases that the offset days also get highlighted, making for some confusing UI as its showing oct 29th and oct 30th selected in the highlighted range, but in the footer you can see that the correct days are selected.

https://github.com/maggialejandro/react-native-calendario/assets/67405221/e4974a79-6f69-4439-98b0-a83d845d9aff

This video showcases when disableOffsetDays is true, but none of the theming objects i can find update that color from white to a specified color

https://github.com/maggialejandro/react-native-calendario/assets/67405221/f885b395-6a92-4a2d-b055-c186790b7262

### Your Environment
    "expo": "^49.0.0",
    "react-native": "0.72.5",
    "react-native-calendario": "^3.3.3",

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

**Comment by maggialejandro** [comment]
Hi @mvolonnino 
Thanks for reporting this issues, try v3.4.0 please

**Comment by mvolonnino** [comment]
Hey @maggialejandro - just updated to the v3.4.0 beta, still same issue unfortunately! Was i supposed to make any other updates? Tried `disableOffsetDays` again and still only 'white', added the `hiddenDayContainerStyle` from the commit, get TS error that it doesnt exist on the `ThemeType`. That didn't work either. Same issues of always white background, or the offset days get highlighted

**Comment by maggialejandro** [comment]
@mvolonnino sorry I forgot to publish the [release](https://www.npmjs.com/package/react-native-calendario/v/3.4.0), try again please

**Comment by mvolonnino** [comment]
Boom that fixed both issues! Awesome thank you so much!
