### ISSUE TITLE
Render Issue when startDate and endDate are not in the current month

### ISSUE THREAD

**Issue by mvolonnino** [maggialejandro/react-native-calendario#346]
### Current behaviour

When utilizing the Calendar in a Gorham/BottomSheetModal, if i select a date or date range that is not within the `currentMonth` (so we can say October), upon opening the Calendar Sheet, it doesn't render any months before the startDate that is applied from the selected date range.

This is not an issue if the selected dates are within the current month, as it renders the month since it looks like its rendering the startDate first in the `FlatList`

Im not sure if there is a prop to disable this behavior but have tried like this with it still not working

```
<Calendar
  key={colors.text.toString()} // force rerender on theme change
  startingMonth={new Date().toISOString()}
  viewableRangeOffset={5}
  startDate={selectedDates.startDate}
  endDate={selectedDates.endDate}
  minDate={new Date()}
  monthHeight={MONTH_HEIGHT}
  numberOfMonths={13}
  onPress={selectDates}
  theme={getCalendarTheme(colors)}
  disableOffsetDays
/>
```

### Expected behaviour

No matter the dates selected, the Calendar list should also start and render with the initial `startingMonth` instead of going off the `startDate` (which i think is correct in marking the calendar right?)

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Screenshots (if applicable)

You can see that on first render or whenever i select dates within the first month, the sheet on next open renders just fine, but if i have any dates selected after the first month that is rendered (which if no props passed in is just the current month), the Calendar doesn't render the current month, Ive noticed that it doesnt render any of the months before the `startDate` prop.

The months before the `startDate` don't render until beginning to scroll on the sheet/calendar list.

https://github.com/maggialejandro/react-native-calendario/assets/67405221/59dd3693-f498-43dc-bfb1-9098d48d80e5

### Your Environment

    "react-native": "0.72.5",
    "react-native-calendario": "^3.4.0",
<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

**Comment by mvolonnino** [comment]
*edit

Some further testing - looks like if the `startDate` is 1 month or ahead of the current date today, the render issue happens above.

So when i select just the date Nov 5th, the render issue _does not_ happen, but if select the `startDate` to be Nov 6h, the render issue _does_ happen

**Comment by maggialejandro** [comment]
Hi @mvolonnino 
could you please share a reproducible example? that would really help debugging the issue

**Comment by maggialejandro** [comment]
I couldn't reproduce the bug 
check this [branch](https://github.com/maggialejandro/react-native-calendario/tree/bugfix/issue-346)

https://github.com/maggialejandro/react-native-calendario/assets/3394748/2d03459d-dc8f-475d-8927-05b263d926d0

**Comment by mvolonnino** [comment]
mhm, in your code it doesn't look like the `Calendar` component wrapped within a `BottomSheetFlatList` as well. Im curious, are you able to scroll through the calendar on an Android device? The issue I have is that the scrolling does not pass through to the `Calendar` component while its wrapped in that `BottomSheetModal`.

Need that type of setup for the Gorham Bottom Sheet to be able to scroll within the Calendar component on Android. iOS worked without doing needing that _workaround_

**Comment by maggialejandro** [comment]
I see, it seems to be a `@gorhom/bottom-sheet` issue on Android.
It makes sense that if you add a scrollable component the calendar won't scroll to the correct month.

You could fork this library and replace Calendar's FlatList with gorhom's `BottomSheetFlatList` instead

**Comment by mvolonnino** [comment]
I just tried and tested with the `BottomSheetFlatList` component, the performance takes a bit of a hit when just plugging that in.

I think a pretty simple and easy fix/workaround could be just exposing the `initialScrollIndex` that can override if one is passed in

```
      initialScrollIndex={
        props.initialScrollIndex ?? !isWeb && !calculateMonthHeightDynamically ? firstMonthIndex : 0
      }
```

when commenting out that line in `Calendar.tsx` line 286, the render issue is gone, and performance stays the same when testing on iOS and Android device.

This way, the `Calendar` can still be used within a `BottomSheetFlatList` in how I have it implemented above, with passing `initialScrollIndex={0}` and  `startingMonth` in conjunction to have it open to the starting month everytime and not worry about scrolling to the selected date.

Do you think that is a valid _fix_ for this specific issue im running into?

**Comment by mvolonnino** [comment]
@maggialejandro  - Let me know if I did everything correct, this is my first time doing anything for open source! I appreciate you responding and helping me out these past couple days 🙌

**Comment by maggialejandro** [comment]
awesome, thank you!

**Comment by chganesh** [comment]
@maggialejandro @mvolonnino 
we need the calendar to display the current month when opened but with the ability to go back in time and select a previous date. current month should be display first and scroll should be top.
