### ISSUE TITLE
Range select is not working (maybe cached onPress)

### ISSUE THREAD

**Issue by vargajacint** [maggialejandro/react-native-calendario#347]
I've tried the official provided example in expo snack, but unfortunately the range select is not working. I've tried to `console.log` the `startDate` and `endDate` in the `onPress` function, and it seems like the value is not updating. 

### Current behaviour

https://github.com/maggialejandro/react-native-calendario/assets/42407460/22ac2314-df39-4fcf-b565-9716a45351bd

### Code sample

```
const App = () => {
  const [startDate, setStartDate] = useState(
   undefined
  );
  const [endDate, setEndDate] = useState(
    undefined
  );

  const handleChangeDate = useCallback(
    (date) => {
      if (startDate) {
        if (endDate) {
          setStartDate(date);
          setEndDate(undefined);
        } else if (date < startDate) {
          setStartDate(date);
        } else if (date > startDate) {
          setEndDate(date);
        } else {
          setStartDate(date);
          setEndDate(date);
        }
      } else {
        setStartDate(date);
      }
    },
    [startDate, endDate]
  );

  return (
    <SafeAreaView>
        <Calendar
          onPress={handleChangeDate}
          startDate={startDate}
          endDate={endDate}
           monthHeight={370}
          numberOfMonths={100}
          initialListSize={4}
          firstDayMonday
          showsVerticalScrollIndicator={false}
          calculateMonthHeightDynamically
        />
    </SafeAreaView>
  );
};

export default App;
```

**Comment by maggialejandro** [comment]
thank you, it's fixed on v3.4.1

**Comment by anija** [comment]
I hope this will be released as soon as possible, since 3.5.0 is broken and I have to dig into closed issue to find this.

**Comment by vargajacint** [comment]
@anija I think it's already released

**Comment by vargajacint** [comment]
Here is my yarn.lock
```
react-native-calendario@^3.4.1:
  version "3.4.1"
  resolved "https://registry.yarnpkg.com/react-native-calendario/-/react-native-calendario-3.4.1.tgz#0520d0061ffe12ab0bb824cc7d1b9b844509d213"
  integrity sha512-KdhxgO+HRATf6KHGUExwvv4jaohpkj2vCjNUTacCln2QWwKw4E+ZdVYutEnaWbwP/f+VwiBcsxTPSgnyla4Kpw==
  dependencies:
    moment "2.29.1"
    react-native-month "^1.6.2"
    
```

And here is my application that using the feature:
![Simulator Screenshot - iPhone 15 Pro - 2023-10-30 at 18 44 45](https://github.com/maggialejandro/react-native-calendario/assets/42407460/0cc28b7c-d2a0-469d-b473-6f46ff2dfb33)

Could you share your code?

**Comment by anija** [comment]
You can succesfully select a startDate in one month and the endDate in the month after?

**Comment by vargajacint** [comment]
@anija Yep!

**Comment by mtsymlov** [comment]
Uploading Simulator Screen Recording - iPhone 14 Pro Max - 2023-12-12 at 15.03.44.mp4…

@maggialejandro This week I've caught the same problem on 3.5.0. It looks as the handler for onPress caches a previous state for months which were not rendered in the first render.

I used the fix which set a pressed value to a separate useState and additional useEffect watched for changes.

**Comment by maggialejandro** [comment]
> Uploading Simulator Screen Recording - iPhone 14 Pro Max - 2023-12-12 at 15.03.44.mp4…
> 
> @maggialejandro This week I've caught the same problem on 3.5.0. It looks as the handler for onPress caches a previous state for months which were not rendered in the first render.
> 
> I used the fix which set a pressed value to a separate useState and additional useEffect watched for changes.

Hi @mtsymlov, the video didn't finish uploading. What props are you using in the Calendar?

**Comment by mtsymlov** [comment]
@maggialejandro 

I've uploaded video to [Google Drive](https://drive.google.com/file/d/1e4UhqxEKpga_NLh0mNAkZCc8c5sWYPjf/view?usp=sharing).

`
<Calendar
        disableOffsetDays={true}
        monthHeight={MONTH_HEIGHT}
        firstDayMonday={true}
        startingMonth={'2023-01-01'}
        numberOfMonths={12}
        showsVerticalScrollIndicator={false}
        onPress={setPressedDate}
        startDate={startDate ? new Date(`${startDate}`) : undefined}
        endDate={endDate ? new Date(`${endDate}`) : undefined}
        contentContainerStyle={containerStyles}
        theme={THEME}
      />
`

**Comment by mtsymlov** [comment]
@maggialejandro my calendar has 12 months, `start_date` and `end_date` is today i.e. December is shown below by default. If I select period from June to December it works okay. But if I select period in January it doesn't work properly.

In `onPress` handler I see that January contains `start_date` and `end_date` from first render, even I changed `start_date` and `end_date` 5 times before.

Please feel free to ask me more about environment or something else.
