### ISSUE TITLE
Custom renderer prop (could be useful for bottom-sheet or flashlist)

### ISSUE THREAD

**Issue by vargajacint** [maggialejandro/react-native-calendario#359]
### Current behaviour

Right now the library is not working on Android with popular [react-native-bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet) library. The reason is, because react-native-bottom-sheet provides a custom FlatList implementation, called `BottomSheetFlatList` and the whole gesture driven scroll event works with that.

### Solution
I've added a custom, optional `renderer` prop to `Calendar` component, and the component decides which renderer should use with the following way:
```
  const {
    ...
    renderer
  } = props;

  const Component = renderer ?? FlatList;
  ...
     return ( <Component ... props /> );
```

### Help needed
Unfortunately I'm not sure what is the best type for this prop. For simplicity I've added this right now: `renderer?: React.ForwardRefExoticComponent<any>`.

### Tests
I've tested this implementation with the previously mentioned react-native-bottom-sheet and flash-list. Unfortunately Flash-list need more workaround to get it work.

### Question
Is there any other way to support this kind of funtionality?

Here is my patch-package:
[react-native-calendario+3.4.1.patch](https://github.com/maggialejandro/react-native-calendario/files/12849582/react-native-calendario%2B3.4.1.patch)

Thank you for helping and maintaining🫶🏻

**Comment by maggialejandro** [comment]
I changed the patch a little bit but still have a couple of TS issues

```typescript
renderer?: ForwardRefExoticComponent<FlatListProps<any>>
```

Issues:

in Calendar.tsx @ ref={listReference}
```
No overload matches this call.
  Overload 1 of 2, '(props: FlatListProps<any> | (Readonly<FlatListProps<any>> & FlatListProps<any>)): FlatList<any> | ReactElement<...> | null', gave the following error.
    Type '{ contentContainerStyle: StyleProp<ViewStyle>; getItemLayout: ((_data: any, index: number) => { length: number; offset: number; index: number; }) | undefined; initialScrollIndex: number; ... 7 more ...; ref: RefObject<...>; }' is not assignable to type 'IntrinsicAttributes & (FlatListProps<any> | (Readonly<FlatListProps<any>> & FlatListProps<any>))'.
      Property 'ref' does not exist on type 'IntrinsicAttributes & (FlatListProps<any> | (Readonly<FlatListProps<any>> & FlatListProps<any>))'.
  Overload 2 of 2, '(props: FlatListProps<any>, context: any): FlatList<any> | ReactElement<any, string | JSXElementConstructor<any>> | null', gave the following error.
    Type '{ contentContainerStyle: StyleProp<ViewStyle>; getItemLayout: ((_data: any, index: number) => { length: number; offset: number; index: number; }) | undefined; initialScrollIndex: number; ... 7 more ...; ref: RefObject<...>; }' is not assignable to type 'IntrinsicAttributes & FlatListProps<any>'.
      Property 'ref' does not exist on type 'IntrinsicAttributes & FlatListProps<any>'.ts(2769)
(property) ref: React.RefObject<FlatList<any>>
```

App.tsx at prop @ renderer={BottomSheetFlatList}
```
Property '$$typeof' is missing in type '<T>(props: BottomSheetFlatListProps<T>) => ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ForwardRefExoticComponent<FlatListProps<any>>'.ts(2741)
index.d.ts(360, 18): '$$typeof' is declared here.
index.tsx(268, 3): The expected type comes from property 'renderer' which is declared here on type 'IntrinsicAttributes & CalendarProps & RefAttributes<FlatList<any>>'
(property) CalendarProps.renderer?: React.ForwardRefExoticComponent<FlatListProps<any>>
````

**Comment by vargajacint** [comment]
I did this as well, but unfortunately I got this error. So this is why I need some help, because this Typescript error is out of my knowledge... Maybe I will spend a couple hours to investigate this error and try to resolve it.
Anyway, what do you think about the whole idea?

**Comment by maggialejandro** [comment]
I played around with this but couldn't find a way to correctly type the renderer prop, [here](https://github.com/maggialejandro/react-native-calendario/commit/273fe7336cd1f43e10021d2e31dc4dacfdb75531) is what I tried..

**Comment by maggialejandro** [comment]
Closing this... feel free to open a PR if you find a working solution

**Comment by elie-chaaban** [comment]
I am facing same issues with gorhom bottom sheet, the calendar is not clickable
