### ISSUE TITLE
Date range selection

### ISSUE THREAD

**Issue by arunkumar-pyt** [maggialejandro/react-native-calendario#371]
I want to select dates like range . Its not working disable range ={false}

**Comment by maggialejandro** [comment]
Hi @arunkumar-pyt 
Could you share a code snippet of how you're using the library? What version are you using?

**Comment by arunkumar-pyt** [comment]
Can you please share sample for date range selection code and single date selection if possible

**Comment by maggialejandro** [comment]
Sorry for the delay, here is an [example](https://github.com/maggialejandro/react-native-calendario/blob/master/example/App.tsx) 
You need to use `disableRange` for single date selection.
Feel free to re-open the issue or create another one
