### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by arunkumar-pyt** [maggialejandro/react-native-calendario#382]
From today afternoon I got except like str. match is not a function (is undefined)

I am using latest version 3.5.0.

Im using latest React native version and Latest Mac OS version

**Comment by arunkumar-pyt** [comment]
Kindly reply me

**Comment by maggialejandro** [comment]
Hi @arunkumar-pyt 
could you check on your yarn.lock or package-lock.json if you have `react-native-month` v1.7.0 installed?
if that's the case, I think we should fix the version on this library

**Comment by arunkumar-pyt** [comment]
export function isValidDate(str: string): str is DateString {
  try {
  return (
    str.match(/^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[01])$/) !== null
  );
  }
  catch(e) {
    return true;
  }
}

having issue on this file , what update have u done, even I try put try catch it open but not clickable date

**Comment by arunkumar-pyt** [comment]
Okie I check with react-native-month v1.7.0

**Comment by maggialejandro** [comment]
> Okie I check with react-native-month v1.7.0

It should be [v1.6.3](https://github.com/maggialejandro/react-native-month/releases/tag/v1.6.3)

**Comment by arunkumar-pyt** [comment]
Okie, kindly be online. because we planned to go live tomorrow morning. Previous we  are using react-native-calendar from Facebook team. but it's not good performance. I believe you to solve

**Comment by arunkumar-pyt** [comment]
Still I got the same Error.

"react-native-calendario": "3.5.0",
"react-native-month": "1.6.3",

**Comment by arunkumar-pyt** [comment]
Kindly give me a solution ?

**Comment by maggialejandro** [comment]
Fixed on v3.5.1

**Comment by arunkumar-pyt** [comment]
Check and confirm @maggialejandro
