### ISSUE TITLE
scrollToIndex out of range

### ISSUE THREAD

**Issue by Jhony-Reyes** [maggialejandro/react-native-calendario#39]
Hi, I tried to use this library, but I get the following error: 
`scrollToIndex out of range: -1 vs 11`
![screenshot_20181018-212254](https://user-images.githubusercontent.com/24459598/47194407-cdcb5500-d31c-11e8-887d-748116e694b8.png)

what am I doing wrong?

this is my code:

```
<Calendar
    onChange={range => console.log(range)}
    startDate="2018-04-30"
    endDate="2018-05-05"
    locale="es"
/>
```
thanks for your help.

**Comment by maggialejandro** [comment]
Can you share the output of ```react-native info```  please?
Thanks

**Comment by maggialejandro** [comment]
Are you using the latest version of this library?
Can you share the output of react-native info please?
Thanks

**Comment by maggialejandro** [comment]
Are you using the latest version of this library?
Can you share the output of ```react-native info``` please?
Thanks

**Comment by maggialejandro** [comment]
I'll closing this, feel free to create a new issue
