### ISSUE TITLE
Property for past days

### ISSUE THREAD

**Issue by VamshiKyra** [maggialejandro/react-native-calendario#47]
Hi,

I want to make past days (in reference to present day) not able to select and want to show the past days with different color so user can understand they are past days. 

I could just supply: 
minDate={this.state.presentdate}  

but I want to show the user past days too.

Thanks!

**Comment by maggialejandro** [comment]
Have you tried styling those days with nonTouchableDayContainerStyle and nonTouchableDayTextStyle ?

**Comment by VamshiKyra** [comment]
nonTouchableDayContainerStyle and nonTouchableDayTextStyle: These are previous months dates. I need past days to be non-touchable. Ex: Today 11-17-2018 User should not able to touch 11-16-2018. 

Is there any property?

**Comment by maggialejandro** [comment]
You can now styles those days using dayOutOfRangeContainerStyle and dayOutOfRangeTextStyle
