### ISSUE TITLE
[Problem] When updating startDate, it does not scroll to that month

### ISSUE THREAD

**Issue by jaydeep987** [maggialejandro/react-native-calendario#59]
I think that's an issue but not sure, guide me if I am wrong.

```
<Calendar
          startDate={formatDate(this.state.currentDate, Formats.YYYYMMDD)}
          startingMonth="1960-01-01"
          numberOfMonths={730}
          monthHeight={450}
          viewableItemsChanged={this.updateCurrentDate}
        />
```

I have other component where I can select month or year. I change the `currentDate` in state when user changes month/year.
But this Calendar view is not updated to that month/year.

I saw source code, I guess issue is in `componentWillReceiveProps`
You're just updating `startDate` and `endDate`. What about `FlatList`? It *won't* scroll automatically if you don't update it.
I think you need to use `scrollToOffset()` to scroll to new date.

**Comment by maggialejandro** [comment]
Hi, thanks for reporting this
I think the best way to do that is to expose FlatList reference. Then you can access Calendar state, calculate the index of the month you need to show and call FlatList scrollToIndex method

**Comment by jaydeep987** [comment]
Thanks for reply!

Yea that's one way. But what I think is, as you're allowing to set start and end dates, it can be updated from parent component any time. I mean it's already a provision to allow to set *start/end dates* and *re-render* `Calendar`, because you update the state of *component* only when *start/end date* are _different_ from _current state_.
```
componentWillReceiveProps(nextProps: CalendarType) {
    const startDate =
      nextProps.startDate && isValidDate(new Date(nextProps.startDate))
        ? moment(nextProps.startDate, 'YYYY-MM-DD').toDate()
        : null;
    const endDate =
      nextProps.endDate && isValidDate(new Date(nextProps.endDate))
        ? moment(nextProps.endDate, 'YYYY-MM-DD').toDate()
        : null;

    if (this.state.startDate !== startDate || this.state.endDate !== endDate) {
      this.setState({
        startDate,
        endDate,
      });
    }
  }
```
So, it we update start/end dates of current viewable month area, then it should be fine. But what if start/end dates are out of viewable area? Then it should automatically scroll to that dates.
I think this should be done internally and user should get this out-of-box!
What do you think?

**Comment by maggialejandro** [comment]
Sorry for the delay, I've been busy
I'll try to finish this in the following days
