### ISSUE TITLE
Can locale support Chinese?

### ISSUE THREAD

**Issue by 278599135** [maggialejandro/react-native-calendario#72]
Can locale support Chinese?

**Comment by maggialejandro** [comment]
Hi! You can use these props to use custom month and weekday names:
https://github.com/maggialejandro/react-native-calendario/blob/master/lib/index.js#L35-L36
Also, if you want locale support you can add it here:
https://github.com/maggialejandro/react-native-calendario/blob/master/lib/utils/date.js
Feel free to send a PR :wink:
