### ISSUE TITLE
Selecting a day, onChange returns day selected - 1

### ISSUE THREAD

**Issue by giacomocerquone** [maggialejandro/react-native-calendario#74]
As the title says, when I select, for example, the 8th of may, in the onChange I receive the 7th of may. Could this have something to do with date locales?

UPDATE: Ok, I didn't notice that parsing the string returned with `new Date(range.startDate)` returns the correct date, so I suppose it is a timezone matter as I was thinking. Could you expand on this a little bit? What I don't get is **why** calling new Date sets it to my timezone in browser but not on android or ios in react native

**Comment by maggialejandro** [comment]
Hi @giacomocerquone. Does this happen when you have remote debugger enabled? [This](https://medium.com/@suyogkrazz/you-should-not-always-rely-on-remote-debugging-react-native-787a850c7ad8) is what is probably happening

**Comment by maggialejandro** [comment]
Closing this, feel free to open another issue
