### ISSUE TITLE
Make certain dates unselectable

### ISSUE THREAD

**Issue by AideProjet** [maggialejandro/react-native-calendario#83]
Hi, 

I'm working on an airbnb-like calendar where the user can select dates to book but I want to make unselectable the dates that are already booked, do you know how I can do that with calendario? 

Thanks, 

Théo

**Comment by maggialejandro** [comment]
Hi Théo, have you tried using `renderDayContent`?

**Comment by pineappleFTW** [comment]
i'm having the same issue, i have use renderDayContent to render but it keeps triggering the parent's touchable opacity, any way to disable it?

**Comment by maggialejandro** [comment]
Ok guys, I will look into this soon
