### ISSUE TITLE
First month as current with the ability to go back

### ISSUE THREAD

**Issue by AideProjet** [maggialejandro/react-native-calendario#95]
Hi, 

Thanks for the library, very appreciated and used in several of our apps in production 🤝

We have some issue right now, we need the calendar to display the current month when opened but with the ability to go back in time and select a previous date. We tried several things with minDate and startingMonth but it doesn't seem to work ... 

Any idea? 

Thanks again, 

Théo

**Comment by sckoh** [comment]
did you find out how to do this?

**Comment by maggialejandro** [comment]
@sckoh The calendar will create a list of months starting with firstMonthIndex and will position itself in the first month of the selected date range.
Let me know if that helps

**Comment by chganesh** [comment]
@maggialejandro 
Hi,
Thanks for the library, very appreciated and used in several of our apps.
we need the calendar to display the current month when opened but with the ability to go back in time and select a previous date. current month should be display first and scroll should be top.

 @maggialejandro @sckoh @minuitagency  help me on this.
thanks in advance

**Comment by maggialejandro** [comment]
> @maggialejandro Hi, Thanks for the library, very appreciated and used in several of our apps. we need the calendar to display the current month when opened but with the ability to go back in time and select a previous date. current month should be display first and scroll should be top.
> 
> @maggialejandro @sckoh @minuitagency help me on this. thanks in advance


A new prop (Date) should be added, which should be used in [getMonthIndex](https://github.com/maggialejandro/react-native-calendario/blob/master/src/components/Calendar.tsx#L83) (instead of localStartDate)

Do you want to create a PR with that feature? (Remember to update the README too)

**Comment by chganesh** [comment]
@maggialejandro  thanks for your response i unable to find your solution. please help me any snippet for this one.

i have one more question is it possible to range selection restriction like 7 days 30 days

**Comment by chganesh** [comment]
@maggialejandro Any update 

> please help me any snippet for this one.
> 
> i have one more question is it possible to range selection restriction like 7 days 30 days

@maggialejandro Any update on this

**Comment by chganesh** [comment]
> @maggialejandro thanks for your response i unable to find your solution. please help me any snippet for this one.
> 
> i have one more question is it possible to range selection restriction like 7 days 30 days

@maggialejandro Please help me on this

**Comment by maggialejandro** [comment]
> @maggialejandro thanks for your response i unable to find your solution. please help me any snippet for this one.
> 
> i have one more question is it possible to range selection restriction like 7 days 30 days

The only way to restrict the selection to 7 or 30 days is to set `minDate` and `maxDate` after selecting a day. 
Or you can do it yourself, for example, after selecting a day, set `endDate` by adding 7 or 30 days.

**Comment by chganesh** [comment]
@maggialejandro 
<Calendar
                        data={[{ id: 'calendar' }]}
                        onPress={handleChangeDate}
                        startDate={range.start}
                        endDate={range.end}
                        startingMonth={moment().clone().subtract(11, 'months').startOf('month').format('YYYY-MM-DD')}
                        monthHeight={370}
                        numberOfMonths={12}
                        renderAllMonths
                        minDate={range.start}
                        maxDate={moment(range.start).clone().add(7, 'days').startOf('day')}
                        initialListSize={12}
                        theme={THEME}
                        showWeekdays={true}
                        firstDayMonday={true}
                        //disableRange={true}
                        markedDays={markedVitalDates}
                        disabledDays={DISABLED_DAYS}
                    />

The only way to restrict the selection to 7 or 30 days is to set minDate and maxDate after selecting a day.
Or you can do it yourself, for example, after selecting a day, set endDate by adding 7 or 30 days 
this solution working fine first time. if i select start  date restrict the selection to 7 remaining days are disabled unable  selecting another disabled day of the month 

https://snack.expo.dev/qxzR3cTtVewpo86p0qBCO?platform=android

**Comment by chganesh** [comment]
> @maggialejandro <Calendar data={[{ id: 'calendar' }]} onPress={handleChangeDate} startDate={range.start} endDate={range.end} startingMonth={moment().clone().subtract(11, 'months').startOf('month').format('YYYY-MM-DD')} monthHeight={370} numberOfMonths={12} renderAllMonths minDate={range.start} maxDate={moment(range.start).clone().add(7, 'days').startOf('day')} initialListSize={12} theme={THEME} showWeekdays={true} firstDayMonday={true} //disableRange={true} markedDays={markedVitalDates} disabledDays={DISABLED_DAYS} />
> 
> The only way to restrict the selection to 7 or 30 days is to set minDate and maxDate after selecting a day. Or you can do it yourself, for example, after selecting a day, set endDate by adding 7 or 30 days this solution working fine first time. if i select start date restrict the selection to 7 remaining days are disabled unable selecting another disabled day of the month
> 
> https://snack.expo.dev/qxzR3cTtVewpo86p0qBCO?platform=android

fixed 

@maggialejandro need one solution by default When I give a start and end date, I am unable to load remaining months' dates. They are not showing up unless the user scrolls.
