### ISSUE TITLE
Render calendar on endDate Month

### ISSUE THREAD

**Issue by eiditakahashi** [maggialejandro/react-native-calendario#98]
After I select start date and end date, when I try to edit dates is it possible to render calendar on end date month?

**Comment by maggialejandro** [comment]
Yep, that could be possible changing these lines.
https://github.com/maggialejandro/react-native-calendario/blob/35c10328879d841a3fab402c886662ff0561cf9c/lib/components/Calendar.js#L121-L131

PRs are welcome :rocket: :wink:
